# Generated by Django 3.2.3 on 2021-06-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
