# Generated by Django 3.2.3 on 2021-05-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Content', models.TextField(max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.user')),
            ],
        ),
    ]
