# Generated by Django 3.2.3 on 2021-05-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_todo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
